### ISSUE TITLE
Problem with tsx files

### ISSUE THREAD

**Issue by dougefr** [imjuni/create-ts-index#11]
Good afternoon

Using the version 1.7.0, files with extension .tsx are being exported with the wrong name of file. 

Example:

![image](https://user-images.githubusercontent.com/8345802/54841696-ae12d100-4cae-11e9-9b11-071277e82ee4.png)

At the version 1.7.0, the index.ts was generated with the content:

```javascript
// created from 'create-ts-index'

export * from './Alert';
export * from './Dialogx';
```

At the version 1.6.1:

```javascript
// created from 'create-ts-index'

export * from './Alert';
export * from './Dialog';
```

**Comment by imjuni** [comment]
Thank you for your interesting

I found bug from extname remove routine.

I fix this issue from 1.7.1.

**Comment by dougefr** [comment]
Hello

I upgraded to 1.7.1 version and the problem still occurs :(

**Comment by imjuni** [comment]
@dougefr 

Sorry for your time waste.

And I found bug from publish script, So I fix and re-publish.

Also test another repo. 

Thank you

**Comment by dougefr** [comment]
Thanks @imjuni , now it is working :+1:
