### ISSUE TITLE
'cti create' failing to find folders on Windows

### ISSUE THREAD

**Issue by MarkNenadov** [imjuni/create-ts-index#12]
In my package.json I have:

`  "scripts": {
    "build": "cti create ./src && tsc",
`

This works perfectly on Mac.  It finds index.ts, builds and traverses a couple of nested subdirectories, properly generate the index.ts files.

However, on Windows, it seems to have a problem with finding the directories. The root index.ts gets properly generated, but each nested directory gets a blank index.ts (even if the directory has typescript files).

(Note: It does work properly if I call "cti create" on each individual subfolder)

Is this a known issue? Are there any workarounds? I'd appreciate some help if possible.

**Comment by imjuni** [comment]
Thank you for your interesting,

I don't have a window machine but I will test window-vm soon

Also I found some bug in this version, I will fix it. (configuration loader path problem)

Plz wait some day

**Comment by imjuni** [comment]
@MarkNenadov I found problem in windows environment, because path.resolve and glob module build path using by path.sep (in window '\') but import syntax only permit '/'

I fix this issue some times later (because I got vacation)

Plz some wait,

**Comment by imjuni** [comment]
hi @MarkNenadov 

I fix this problem in 1.9.1 version

Thank you for waiting

**Comment by imjuni** [comment]
I resolve this issue 16 days ago. I close this issue tomorrow.

FYI
