### ISSUE TITLE
Disable comment in first line

### ISSUE THREAD

**Issue by Buszmen** [imjuni/create-ts-index#13]
Can we have an option to generate file without the comment in the first line?
```// created from 'create-ts-index'```

**Comment by imjuni** [comment]
@Buszmen Thank you for your interesting, 

I will add option remove comment line

plz wait

**Comment by imjuni** [comment]
@Buszmen Thank you for waiting, long time

I add new option in `1.10.0`

You can use new option `withoutcomment` in `1.10.0`. This option remove comment that top of line in index.ts file

**Comment by Buszmen** [comment]
Somehow I am unable to use this option. 
I have `cti` installed globally using npm. When I use `cti --help` I can see the first option:
```
--1.7.2             version                                          [boolean]
```

It's sometimes `0.0.0` or `1.0.0` depending where I am in a folder structure of my project (weird, right?). Anyway - is this supposed to tell me the version? I checked the `package.json` where it is installed and it says `1.10.1` so it's definitely the newest version installed. 

I don't see this opion in `help` but I tried `--withoutcomment` and `-w` and it still adds the comment and this option doesn't show in the `verbose` even. :(

**Comment by bjleeya** [comment]
@Buszmen TY your interesting!

I found some bug in cti command-line tools. 

I fix this issue in today.

**Comment by imjuni** [comment]
@Buszmen Fix & Publish, 

You can see valid version and help command

```bash
$ cti create help
# or
$ cti help
```

**Comment by imjuni** [comment]
@Buszmen TY your feedback!

**Comment by Buszmen** [comment]
@imjuni Thank you, finally it works perfectly! :+1:
