### ISSUE TITLE
Skipped a file with the word index in the filename

### ISSUE THREAD

**Issue by virkt25** [imjuni/create-ts-index#14]
I had a file named: `customer-health-index.ts` and it was not included in the auto-generated `index.ts`. After I renamed the file to exclude the word `index`, it showed up in the generated `index.ts`.

**Comment by imjuni** [comment]
Hi @virkt25 

I fix this bug in `1.9.1`

Thank you for waiting

**Comment by virkt25** [comment]
Thanks for your hard work and speedy fix as always!
