### ISSUE TITLE
No generating index.ts for between directories

### ISSUE THREAD

**Issue by jonas-lauber** [imjuni/create-ts-index#2]
Hi, thanks for your great script, that was exactly what I needed!!
I ran into a little problem today. I noticed that no index.ts where generated for empty directories that where part of a longer path. For instance with the given structure:

A
|
B
|
file.ts

An index.ts will be generated in B/ (next to file.ts) and in root (next to A/), but none will be in A/. Something like:

   A  + index.ts
      | 
     B
   |       
files.ts + index.ts

I first thought this wasn't implemented, but I have been through the code and saw the logix was actually there. After some debugging I think I understood what was the problem: 

In allTsFiles after calling glob I had "A/B/test.ts", but later to compute dupLibDirs, you are using path.spec that was for me (on Windows) "\". When I replaced "path.spec" with "/" everything was working as expected. I looked up on the documentation of glob, and if I understood properly, the result from glob always is with "/": https://github.com/isaacs/node-glob.
In this case one should only use "/" instead of "path.sep". 

What do you think ?

**Update**: I was a bit quick and actually just replacing path.sep with "/" doesn't work as you are using other path function like patj.join(...) that are internally using path.sep... So a nice and robust way to correct the problem for windows users would be to do:

const allTsFilesNormalized = allTsFiles.map((file) => path.normalize(file));

**Comment by imjuni** [comment]
I understand your problem Also I agree that is problem. And I fix that soon. Thank.

**Comment by bjleeya** [comment]
Dear jonas,

I fix this problem in ver 1.5.0.

thank you.

**Comment by imjuni** [comment]
dear @jonas-lauber ,

I fix this problem in version 1.5.0.

Thank you
