### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by bharatpatil** [imjuni/create-ts-index#21]
It would be great if it could sort the exports as well.

**Comment by imjuni** [comment]
@bharatpatil Hi,

create-ts-index already sort element, see below

```ts
// from src/commands/CreateCommandModule.ts
excludePatternFilteredDirs.sort();
```

But not shake different category (file, directory).

If you want sort every element? (mixed sorting file, directory)

**Comment by imjuni** [comment]
I want to close this issue, plz feedback.

I will close 1~2 week after. Check it plz :)

**Comment by imjuni** [comment]
Already support sorting, Closed.
