### ISSUE TITLE
Cannot have file and dir with same name

### ISSUE THREAD

**Issue by OmgImAlexis** [imjuni/create-ts-index#24]
When you have a dir and a file with the same name the export breaks.

I got the following as I had a dir and a file called `parse-domain`.
```ts
// created from 'create-ts-index'

export * from './parse-domain';
export * from './filter-devices';
export * from './get-pci-devices';
export * from './hypervisor';
export * from './parse-domain';
export * from './parse-domains';
```

I would have expected to see this instead to prevent the issue.
```ts
// created from 'create-ts-index'

export * from './parse-domain';
export * from './filter-devices';
export * from './get-pci-devices';
export * from './hypervisor';
export * from './parse-domain.ts';
export * from './parse-domains';
```

**Comment by imjuni** [comment]
Can you tell me file structure? 

Like this? How to store same name file in directory?

```
src/
  parse-domain.ts
  parse-domains.ts
```

**Comment by OmgImAlexis** [comment]
Yes there’s also a directory in there called parse-domain hence the issue.

**Comment by imjuni** [comment]
Already exists target file, will create backup file.

**Comment by OmgImAlexis** [comment]
What? Was this meant to be an answer to another issue?
