### ISSUE TITLE
Shouldn't touch existing files

### ISSUE THREAD

**Issue by OmgImAlexis** [imjuni/create-ts-index#25]
Without a config this should leave all existing `index.ts` files alone unless they contain the `// created from 'create-ts-index'` header.

**Comment by imjuni** [comment]
Hi @OmgImAlexis 

Set option `withoutComment: true`, Thx

**Comment by OmgImAlexis** [comment]
This should be on by default.

**Comment by imjuni** [comment]
Hi @OmgImAlexis 

Why this option is default? I think that is difference auto created file and programmer created. Comment show difference. If you want, you add `.ctirc` file or add cli option. And that change many people has confused. Thx.

**Comment by OmgImAlexis** [comment]
When I run without any config it’ll delete my index.ts files. This should not happen.

**Comment by imjuni** [comment]
HI @OmgImAlexis 

Thx feedback. I fix that already exists index.ts file, cti not delete.

**Comment by OmgImAlexis** [comment]
So the option isn't needed then?

**Comment by OmgImAlexis** [comment]
Yep just checked it's still an issue.

I ran `./node_modules/.bin/cti create ./src`, I have a file `./src/index.ts` which has no `// created from 'create-ts-index'` command anywhere. Yet it was updated. This should not be the default.

If I hadn't been using git or if I hadn't committed before running this I'd be screwed as my whole file would have been replaced.

**Comment by OmgImAlexis** [comment]
Okay I think you've completely misunderstood me.

From what I can see `withoutComment` only changes if the comment is added to the file.

My issue is it shouldn't touch files that **DON'T** have the comment. Meaning it shouldn't override my code if it's in a `index.ts`.

**Comment by imjuni** [comment]
@OmgImAlexis 

Thank, I understood your problem. And I agree that is problem overwrite index.ts file. 

But I think **index.ts** file something special meaning, Node.js reference default file. Default mean that default export or default code, etc. create-ts-index `create` mode use default export feature. So you can use create-ts-index `entrypoint` mode. `./node_modules/.bin/cti entrypoint ./src` . But create mode must create index.ts file every directory. 

I concern about solution overwrite problem. Thank.

**Comment by imjuni** [comment]
Fixed

**Comment by OmgImAlexis** [comment]
The solution is to only change the file if it has the comment you add or if the file doesn’t exist.

If it does exist and there’s no comment then don’t touch it.
