### ISSUE TITLE
Should ignore empty folders and files

### ISSUE THREAD

**Issue by Fibs7000** [imjuni/create-ts-index#26]
It should ignore empty folders and files. 
If an file is empty or a directory is empty or a tree of directories has no files they should not be exported. 
If not typescript will throw errors.

Further an Default export implementation would be nice. 
Like: export { default as FileName} from './FileName'; if a default export exists

**Comment by imjuni** [comment]
Hi @Fibs7000 

Thx your feedback.

I think, `cti` find *.ts or *.tsx file using by fast-glob. So empty folder not include. 

If you can describe file & directory structure and content, I can't fix that.

And default exportation, I concern about it. But I don't choose method, how can find that file have default exportation. (think, I will use tsc)
