### ISSUE TITLE
Should not create index.ts files alongside an index.tsx one

### ISSUE THREAD

**Issue by GideonPARANOID** [imjuni/create-ts-index#27]
I have a directory like this:
```ts
components/
index.tsx
```
Running `cti` leaves me with:
```ts
components/
index.ts
index.tsx
```

Where `index.ts`:
```
export * from './components';
```

Since `cti` doesn't recognise the `index.tsx` file, & the `index.ts` file overrides it as the default in the directory, anything exported by `index.tsx` is lost.

**Comment by imjuni** [comment]
HI @GideonPARANOID,

`cti` ignore `index.*` file. Because include `index.ts` or `index.tsx` that easily create circular dependency. But I think `index.tsx` something difference. I concern about it. 

Thx your feedback.

**Comment by imjuni** [comment]
Hi @GideonPARANOID 

`create-ts-index` don't know what file have export statement. So this issue solve very hard. 

I create new cli tools for export file generation. [ctix](https://github.com/imjuni/ctix) use TypeScript Compiler API. I think ctix solve this problem.

Thank you.
