### ISSUE TITLE
Make file name for entrypoint.ts configurable

### ISSUE THREAD

**Issue by marvinscharle** [imjuni/create-ts-index#29]
Currently, when using `cti entrypoint`, it is creating a `entrypoint.ts` file. 

There is currently no way to specify another name for the file. 

Can you add this feature, so that the file `entrypoint.ts` can be named somehow else (e.g. `base.ts`)?

[This is the corresponding line](https://github.com/imjuni/create-ts-index/blob/94169f44da3253d6694a8f9c9bf8d1ff832c2ad2/src/commands/EntrypointCommandModule.ts#L201-L202). 

If you want, I can open a PR for that.

**Comment by imjuni** [comment]
Thank you for feedback!

I will update this feature in 04-15 KST, But you want this feature more early, sure PR create!

Thank you :)

**Comment by imjuni** [comment]
Hi @marvinscharle.

I add new option **output** in _1.13.0_

Thank you :)

**Comment by marvinscharle** [comment]
Thanks!
