### ISSUE TITLE
error in Ubuntu 

### ISSUE THREAD

**Issue by hiro5id** [imjuni/create-ts-index#32]
The `--harmony` option is causing a problem in my Ubuntu Linux. When i run cti in command line I get error:
```
/usr/bin/env: 'node --harmony': No such file or directory
```

I have added comment in source code here: https://github.com/imjuni/create-ts-index/commit/18eb3e8579d16627c9481d6ef663f8e6cb5a7a16#r38731519

This is the same problem as this: SpencerCDixon/redux-cli#42

**Comment by imjuni** [comment]
@hiro5id Hi

Thank you for your feedback,

I think same @yedlosh, direct calling create another problem. 

But create-ts-index cli cti can run without `--harmony` option. 

I can remove `--harmony` option immediately. Is this work help to solve Ubuntu problem?

**Comment by kyarunts** [comment]
I have the same issue.
Calling node with the harmony flag causes an issue on Linux machines.
I have downgraded to version 1.12.0 and could bypass the error.
However, seems tslib version has been updated recently and the new version is conflicting with v1.12.0.

**Comment by imjuni** [comment]
Dear @hiro5id @kyarunts 

I remove harmony flag in executable.

Thank you for your feedback!

**Comment by imjuni** [comment]
Hi

I remove harmony option in cli script. 

So I close this issue +1 day after. 

Thank you your feedback!

**Comment by imjuni** [comment]
I close this issue, maybe raised same issue, create new issue. 

Thank you.
