### ISSUE TITLE
Is it possible to limit the depth?

### ISSUE THREAD

**Issue by good-idea** [imjuni/create-ts-index#33]
I'd love to use this to only generate a single `index.ts` file for one directory (`./src/components/index.ts`), without creating files for all of the subdirectories, i.e. `./src/components/Button/index.ts`, `./src/components/Forms/index.ts`.

Is it possible to do this with the fileExcludesPatterns option? I can't seem to figure it out.

**Comment by imjuni** [comment]
@good-idea Thank you for feedback.

create-ts-index support exclude directory by excludes option.  Like [this](https://github.com/imjuni/create-ts-index#cli)

```
cti create -n -e @types,typings,__test__,__tests__,pages ./src
```

But, this option dosen't convenient for you. because **excludes** option can't support glob pattern.
