### ISSUE TITLE
Is it possible to add the ability to generate index files for d.ts files?

### ISSUE THREAD

**Issue by erics112** [imjuni/create-ts-index#34]
Hello,

I've been working on a project where I have a folder with types/generated and within that has a bunch of .d.ts files exporting types. I am trying to use this tool for generating the index files but there doesn't seem to be a way to do so for these file types.

I tired allowing the types folder to be used using the cli, I even made a completely new folder called `experiment` and put all the `.d.ts` files in there and an index file still wasn't created for them.

I found this part of the code which may be related, where it's filtering .d.ts files and was wondering if there's a way around doing that? 
`line 50 in create-ts-index/src/commands/CommandModule.ts`

```typescript
// Step 3, remove declare file(*.d.ts)
.filter((filename) => !filename.endsWith('.d.ts'))
```

Also, is there a reason for removing the `.d.ts` files? I ask because there may be insight into how `.d.ts` files should be properly handled when it comes to creating index files for them that I may be missing.

Thanks for the help.

**Comment by imjuni** [comment]
@erics112 Thank you for detail feedback

I create this package in TypeScript 2.x. TypeScript 2.x raise error by don't have export `d.ts` file. 

```ts
declare module 'create-ts-index' {
    // some type definition ...
}
```

Example declaration file cause error from TypeScript 2.x.

**Comment by imjuni** [comment]
Hi @erics112 

I create new tools for export file creation. [ctix](https://github.com/imjuni/ctix) using TypeScript compiler API. Also don't except `.d.ts` file. I this ctix help to solve this issue. 

Thank you.
