### ISSUE TITLE
[Monorepo] Sibling directory index.ts deleted when using cti clean

### ISSUE THREAD

**Issue by BitForger** [imjuni/create-ts-index#38]
Hi,

Just wanted to drop this in as a potential bug that you may wish to resolve. When using `cti clean .` in a monorepo it can cause an `index.ts` file created in a sibling directory to the package the command is run in to be deleted. I had the following scenario.

```
.
└── packages/
    ├── app/
    │   ├── src/
    │   │   └── main.ts
    │   ├── .ctirc
    │   └── index.ts
    └── lib/
        ├── index.ts
        └── src/
            ├── some/
            │   └── index.ts
            ├── other/
            │   └── index.ts
            └── directories/
                └── index.ts
```

## Steps:
1. Navigate to `packages/app`
2. Run `cti clean .`

## Results:
`cti` would clean the app project correctly but it would also travel to the `lib` package and delete the root index.ts file (`packages/lib/index.ts`).

I could be totally off on this, but I believe it might be something to do with the below glob pattern.

https://github.com/imjuni/create-ts-index/blob/7269aa341553db71e7e7aceeb7eadb9039453ba0/src/commands/CleanCommandModule.ts#L41

## Workaround:
I was able to put in a workaround by calling clean with `./src` as the directory to work in like so: `cti clean ./src`.

**Comment by imjuni** [comment]
Hi, @BitForger 

Thank your feedback.

I will check directory glob pattern.  And plz check [ctix](https://github.com/imjuni/ctix). ctix use `tsconfig.json` configuration file. More easy and convenient Tool.

Thank you!
