### ISSUE TITLE
Option -q

### ISSUE THREAD

**Issue by Friedoo** [imjuni/create-ts-index#40]
Hi,

I have a problem with the quotes option. I am using create-ts-index in the scripts section of my package.json. Somehow I am unable to force it to generate index.ts with double quotes inside.

currently I am using this command:
"build-indexes": "node node_modules/create-ts-index/dist/cti.js entrypoint -b -o index.ts -w ./src/data-model && ..........

adding the quotes option doesnt work:
"build-indexes": "node node_modules/create-ts-index/dist/cti.js entrypoint -q \\" -b -o index.ts -w ./src/data-model && ..........

how can I specify a double quote character?
alternatively an option -qd could solve the problem as well :)

thank you very much!

**Comment by imjuni** [comment]
@Friedoo 

Did you try `cti.js entrypoint -q '"' -b -o index.ts -w ./src/data-model ... ` ?

And I recommand use [ctix](https://github.com/imjuni/ctix).

**Comment by Friedoo** [comment]
Yes I tried it but doesnt work inside package.json script section... :(

**Comment by imjuni** [comment]
@Friedoo 

That is problem of npm script. If you add option to npm script, you have to that,

```bash
npm run cti -- entrypoint -q '"' -b -o index.ts -w ./src/data-model ...
```

Important `--` . Because npm script will remove option before `--` charactor.

**Comment by Friedoo** [comment]
Hi,

no that doesnt work.

"build-indexes": "node node_modules/create-ts-index/dist/cti.js entrypoint -- -q '\"' -b -o index.ts -w ./src/data-model && ..........

**Comment by imjuni** [comment]
@Friedoo 

Try this, 

```
"build-indexes": "node node_modules/create-ts-index/dist/cti.js -- entrypoint  -q '"' -b -o index.ts -w ./src/data-model &&
```

or 

```
npx cti init .
```

After edit .ctirc file your configuration include quote option.
