### ISSUE TITLE
Folder depth

### ISSUE THREAD

**Issue by Friedoo** [imjuni/create-ts-index#41]
Hi,

is there a possibility to constrain the scan of the subfolders to a given depth? Currently it generates the index for all exports found anywhere in the folder structure. I would like to generate an index for exports found in subfolders (1st level) but ignore export in subfolders 2nd level and below (i.e. I want everything below a given folder level not to be "visible" through the generated index file).
An option like -d for depth could be a solution: -d 0 for the specified path only, -d 1 to include direct subfolders but none of their child folders, -d 2 for...etc.

Any chance to get such an option? :) Thank you!

**Comment by imjuni** [comment]
@Friedoo 

Thank your feedback.

I recommand use [ctix](https://github.com/imjuni/ctix). ctix can read target file from tsconfig.json file. But cti create index.ts file some routine (directory, filename etc) so some feature can't support it.

**Comment by Friedoo** [comment]
Thanks for the feedback but I think ctix cant solve my problem folder problem either.

**Comment by imjuni** [comment]
@Friedoo 

ctix support .ctiignore file (.ctiignore format exactly same .gitignore) in each directory. You can pass option for exclude some directory. I think `.gitignore` or `.ctiignore` file more convenient include/exclue file. Also you don't want add `.ctiignore` file vcs, This time you can add `.gitignore`. For example `**/.ctiignore`. 

Thank you.
