### ISSUE TITLE
Creates a .bak file automatically

### ISSUE THREAD

**Issue by Vaasu-Dhand** [imjuni/create-ts-index#44]
When I run ctx create ./directoryPath , it often creates a .bak file automatically. Here's a screenshot
![image](https://user-images.githubusercontent.com/64599364/112375674-8aede280-8d09-11eb-94cb-5f4d4244ce0b.png)

**Comment by tokarchyn** [comment]
Hi @Vaasu-Dhand, did you try to use "-b" argument in CLI or "withoutBackupFile" from code?

**Comment by Vaasu-Dhand** [comment]
So, this is intended behavior after all. I thought there's a bug or something. Thanks mate!
