### ISSUE TITLE
merge dependency severe vulnerability

### ISSUE THREAD

**Issue by pabelnl** [imjuni/create-ts-index#47]
The package is using an outdated version of `merge`, see screenshot below:

<img width="497" alt="Screen Shot 2021-05-04 at 4 35 50 PM" src="https://user-images.githubusercontent.com/19191505/117066501-cdd2ab00-acf6-11eb-805a-583cbb0ca861.png">

**Comment by BitForger** [comment]
I think technically this repo is considered legacy and isn't be actively maintained according to this:
https://github.com/imjuni/create-ts-index/issues/38#issuecomment-685386072

**Comment by pabelnl** [comment]
Thanks, Will take a look
