### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by fboucquez** [imjuni/create-ts-index#51]
There are several security fixes, one I cannot upgrade in my local package loc.

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ merge                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.1.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ create-ts-index [dev]                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ create-ts-index > merge                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1666                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 717 scanned packages
  1 vulnerability requires manual review. See the full report for details.

Great tool! Thanks

**Comment by imjuni** [comment]
Hi, 

I have update dependency, thank you
