### ISSUE TITLE
[BUG] `cti` creates `export` statements for folders that are not modules.

### ISSUE THREAD

**Issue by leonardoraele** [imjuni/create-ts-index#56]
I have a folder `src/types`  in my project. It contains only `.d.ts` files with type definitions of third party packages that don't have type definitions.

`cti` correctly ignores the `.d.ts` files and does NOT create a `src/types/index.ts` file. However, it DO add a `export * from './types';` line to `src/index.ts`, which causes the following compilation error:

```
src/index.ts:6:15 - error TS2307: Cannot find module './types' or its corresponding type declarations.

6 export * from './types';
```

This happens because the `src/types` folder is not a [module](https://www.typescriptlang.org/docs/handbook/modules.html).

The workaround for me was to create an empty module so that `src/types` became an actual module:

```typescript
// src/types/_.ts
export default undefined;
```

Thought this workaround makes the project compile, I end up with a lot of useless files in my build:

```
dist/types/_.d.ts
dist/types/_.d.ts.map
dist/types/_.js
dist/types/_.js.map
dist/types/index.d.ts
dist/types/index.d.ts.map
dist/types/index.js
dist/types/index.js.map
```

**Comment by imjuni** [comment]
Hi, create-ts-index only dependent on directory structure. So create-ts-index cannot detect declaration file. You can set exclude directory to dist or use [ctix](https://github.com/imjuni/ctix).
