### ISSUE TITLE
Create a single index.ts only

### ISSUE THREAD

**Issue by fennecbutt** [imjuni/create-ts-index#6]
Is there the option to create a single index.ts under the targeted src folder?

At the moment it creates an index.ts in every subfolder, and then a main index.ts in the subfolder. It would be much tidier to have the option to generate an index.ts in your src folder that imports anything that is exported in files from any subfolder.

I have a lot of folders with just 1 file in them, so it ends up really messy having an index.ts file in every single subfolder.

**Comment by imjuni** [comment]
If you want single export file, use entrypoint sub-commands. entrypoint sub-commands generate only one file in src.

**Comment by imjuni** [comment]
1.5.0, 1.5.1 version entrypoint mode resolve your problem. I close this issue. thank you.
