### ISSUE TITLE
Incorrect docs for --withoutBackupFile

### ISSUE THREAD

**Issue by chriswoodie** [imjuni/create-ts-index#65]
The correct argument to not generate a backup file seems to be `--withoutbackup` and not `--withoutBackupFile`.

Running `node ./node_modules/create-ts-index/dist/cti.js entrypoint ./libs/${lib.name}/src -o index.ts --withoutbackup --fileexcludes test-setup.ts` works but `node ./node_modules/create-ts-index/dist/cti.js entrypoint ./libs/${lib.name}/src -o index.ts --withoutBackupFile --fileexcludes test-setup.ts` does not.

**Comment by imjuni** [comment]
@chriswoodie Thank you very much for your feedback. However, please note that `create-ts-index` has a successful successor called [ctix](https://github.com/imjuni/ctix) and ctix is actively maintained. If there is any reason why you cannot migrate from create-ts-index to ctix, please let us know and I will add the feature to ctix.
