### ISSUE TITLE
Generated index file does not append `.js` or `.mjs` extensions for ECMAScript imports when using `node16`/`nodenext` module resolution

### ISSUE THREAD

**Issue by jkhaui** [imjuni/create-ts-index#67]
Thanks for the amazing package! Works like a charm for the most part.

The issue I'm facing is basically as stated in the title. 

Fixing this problem would also help future-proof this tool as ES modules become more widely standardised & adopted.

Basically, modules exported from a `.ts` or `.tsx` file extension should have the `.js` extension appended to the path in the generated index file. There's also the `.mts` extension which similarly should have `.mjs` appended to the module's import path.

E.g. If we have the named export `{ helloWorld }` in the path `src/hello-world.mts`, it should appear as `export * from "./hello-world.mjs"` in `src/index.ts`.

Here's a screenshot:

![image](https://github.com/imjuni/create-ts-index/assets/36477474/074b47e5-ee39-4788-ac0d-4ccd181cdf27)

Just let me know if I can help or open a PR, thanks

**Comment by imjuni** [comment]
@jkhaui Hi,

I create next version of create-ts-index that is [ctix](https://github.com/imjuni/ctix).

And this repo is will be maintenance mode. Because directory and filename scan apporach have much constraint than using compiler API. Thank you for your comment.

Thank you.
