### ISSUE TITLE
Clean doesnt include ingnore list

### ISSUE THREAD

**Issue by Samuel-Morgan-Tyghe** [imjuni/create-ts-index#68]
I have a code gen tool that generates my indexes
I have a index creation tool

this tool overwrites the indexes of my code gen tool - because of the nature of code gen tools all files in the directory should be ignored by lining and prettier tools . the problem I have is that I can't select double quotes in the cti config + I cant automatically fix it with a post lint cleanup.

Please either include support to change quotes or include the ignore lists to the cti clean function

**Comment by imjuni** [comment]
@Samuel-Morgan-Tyghe Hi,

This project is in maintenance mode, and I am developing its successor, [ctix](https://github.com/imjuni/ctix). If your goal is to change the quotation marks, you can use the `--quote` option to use double quotes. For any other needs, please consider using [ctix](https://github.com/imjuni/ctix). Thank you!
