### ISSUE TITLE
1.5.0 breaking change

### ISSUE THREAD

**Issue by virkt25** [imjuni/create-ts-index#7]
Breaking change should've been released as a MAJOR version!

Or at the very least the package should've provide backwards compatibility by honouring `cti ./src` as `cti create ./src`

**Comment by imjuni** [comment]
@virkt25 

Your right, 

But I already release. So I found solution for no sub-command (default sub-command).

Thank you.

**Comment by imjuni** [comment]
dear @virkt25  

I add default sub-command in version `1.6.1`.

Thank you for your proposal.
